plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.japanesetokenizer'
version = '1.0.0'

android {
  namespace "expo.modules.japanesetokenizer"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
    consumerProguardFiles 'proguard-rules.pro'
  }
}

dependencies {
  implementation 'com.atilika.kuromoji:kuromoji-ipadic:0.9.0'
}
