plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}
group = 'expo.modules.digitalink'
version = '1.0.0'
android {
  namespace 'expo.modules.digitalink'
  defaultConfig { versionCode 1; versionName '1.0.0' }
}
dependencies { implementation 'com.google.mlkit:digital-ink-recognition:19.0.0' }
